---
# tasks file for install-socat

- block:
  - name: Check socat exists
    shell: command -v socat
    failed_when: false
    changed_when: false
    register: command_socat
  - block:
    - name: Create download directory
      file:
        dest: "{{ tmp_dir }}/socat"
        state: directory

    - name: Retrieve socat tarball
      get_url:
        url: "{{ archive_location }}"
        dest: "{{ tmp_dir }}/"
      register: retrieve_socat_tarball

    - name: Unarchive socat tarball
      shell: "bsdtar -xf {{ retrieve_socat_tarball.dest }} -C {{ tmp_dir }}/socat --strip-components=1"
      register: unarchive_socat_tarball

    - name: Configure
      shell: "cd {{ tmp_dir }}/socat && ./configure"

    - name: Make
      shell: "cd {{ tmp_dir }}/socat && make"

    - name: Move to install directory
      copy:
        src: "{{ tmp_dir }}/socat/socat"
        dest: "{{ install_dir }}"

    - file:
        path: "{{ install_dir }}/socat"
        state: file
        mode: u=rwx,g=r-x,o=r-x
    when: command_socat.rc != 0
  when: ansible_os_family == "Darwin"



